include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore

linter:
  rules:
    # - always_use_package_imports
    # - avoid_dynamic_calls
    # - cancel_subscriptions
    # - close_sinks
    # - prefer_const_constructors
    # - prefer_const_declarations
    # - require_trailing_commas
